default: &default
  adapter: postgresql
  encoding: unicode
  username: ''
  password: ''
  pool: 8
  timeout: 5000
  reaping_frequency: 60

development:
  <<: *default
  database: db/bzn_dev_move_fast

test:
  <<: *default
  database: db/bzn_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
